version: '3'
services:
  elastic:
    image: elasticsearch:7.17.8
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1000m -Xmx1000m
    ports:
      - 9200:9200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:9200 | grep -q 'HTTP/1.1 200 OK'",
        ]
      interval: 1s
      timeout: 5s
      retries: 120
  db:
    image: postgres:13
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./.env.db
    depends_on:
      - elastic
  etl:
    build: .
    container_name: etl
    env_file:
      - ./.env
      - ./.env.db
    depends_on:
      elastic:
        condition: service_healthy
volumes:
  elastic_data:
  postgres_data:

